# Generated by Django 3.2.6 on 2021-10-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('nombre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('cantLikes', models.IntegerField(default=0)),
                ('cantVistas', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('nombre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('cantLikes', models.IntegerField(default=0)),
                ('cantVistas', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('avatarSong', models.ImageField(blank=True, null=True, upload_to='')),
                ('song', models.FileField(upload_to='')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('albumArtista', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Servicios.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('nombre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('cantLikes', models.IntegerField(default=0)),
                ('cantVistas', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('imagengenero', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('nombre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('cantLikes', models.IntegerField(default=0)),
                ('cantVistas', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('nombreArtista', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidoArtista', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_playlist', models.CharField(choices=[('Antes 1960', "Before 60's"), ('1960 - 1980', "60's - 70's"), ('1980 - 2000', "80's - 90's"), ('2000 - actualidad', "2000's - 2020's")], default='Unknown', max_length=100)),
                ('canciones', models.ManyToManyField(to='Servicios.Canciones')),
                ('musicos', models.ManyToManyField(to='Servicios.Musico')),
            ],
        ),
        migrations.AddField(
            model_name='canciones',
            name='artist',
            field=models.ManyToManyField(default='Unknown', to='Servicios.Musico'),
        ),
        migrations.AddField(
            model_name='canciones',
            name='genderSong',
            field=models.ManyToManyField(default='0', to='Servicios.GeneroMusical'),
        ),
        migrations.AddField(
            model_name='album',
            name='generos',
            field=models.ManyToManyField(to='Servicios.GeneroMusical'),
        ),
        migrations.AddField(
            model_name='album',
            name='musico',
            field=models.ManyToManyField(to='Servicios.Musico'),
        ),
    ]
